### ISSUE TITLE
펜스 퀘스트 - 수집가 미션 중에 번역 오류 발견함

### ISSUE THREAD

**Issue by Dayworlds** [GoLani11/GoLani.KoreanModFix#1]
![2024-11-14](https://github.com/user-attachments/assets/de7c5330-722b-4776-a752-601a45992ec8)

제보할 텍스트: (황금 1GPhone 스마트폰) 건네주기
                      (Hand over the Golden 1GPhone smartphone)
                      (Hand over the Golden 1GPhone smartphone)

내용 설명: 다른 텍스트는 문제가 없는데 황금 1GPhone 스마트폰 건네주기 만 문제가 있는거 같습니다.

수정 예상 내용: (황금 1GPhone 스마트폰) 건네주기
                       (Hand over the Golden 1GPhone smartphone)

**Comment by GoLani11** [comment]
제보 감사합니다! 바로 수정했고 다음 SPT 3.10 업데이트 때 같이 업데이트하겠습니다.
